### ISSUE TITLE
Running / testing

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/ChRIS_ui#270]

**Comment by sherrif10** [comment]
Hello @rudolphpienaar  is this ticket still available. i would to dive into it probably adding more info on to it would be amazing.

**Comment by jennydaman** [comment]
@sherrif10 this is just a placeholder issue.

Currently, the front-end does not have any unit tests. Are you interested in helping us set up QA? One possible contribution you can make regarding this issue is configuring a testing framework for this project for unit testing and snapshot testing. Chat with me on Matrix if you'd like to discuss.
