### ISSUE TITLE
Adding eye button in the login form 

### ISSUE THREAD

**Issue by aashimawadhwa** [FNNDSC/ChRIS_ui#389]
Adding an eye button to login page just like signup can make logging in convenient for user .

It looks like this-

![Screenshot from 2022-04-09 03-29-10](https://user-images.githubusercontent.com/73706697/162538099-49e1fbd3-ac17-4486-96ee-bdcfe1180fe3.png)

Can we make something like this-

![broooo](https://user-images.githubusercontent.com/73706697/162538109-024436c9-b544-4656-abd2-b25932394de5.jpg)

**Comment by username-copied** [comment]
Hello @aashimawadhwa, I would like to solve this issue. Can you assign it to me?

**Comment by aashimawadhwa** [comment]
> Hello @aashimawadhwa, I would like to solve this issue. Can you assign it to me?

I'm a fellow contributor it can be only assigned by maintainer.

**Comment by username-copied** [comment]
> > Hello @aashimawadhwa, I would like to solve this issue. Can you assign it to me?
> 
> I'm a fellow contributor it can be only assigned by maintainer.

Okay

**Comment by sherrif10** [comment]
Hello @jennydaman . this issue looks awesome. can  you assign it to me.

**Comment by aparna-bhatt** [comment]
@jennydaman I have made a pull request please see to it.Link to my PR https://github.com/FNNDSC/ChRIS_ui/pull/407

**Comment by Akanksha2403** [comment]
Hii, can you assign it to me.

**Comment by jennydaman** [comment]
This is a duplicate of https://github.com/FNNDSC/ChRIS_ui/issues/230 but it hasn't been fixed.

I've assigned the issue to @aashimawadhwa because she is the one who proposed it.

@aparna-bhatt, I am obligated to let @aashimawadhwa attempt a solution for this issue before considering your PR.

@username-copied, @sherrif10, @Akanksha2403, please ask @aashimawadhwa if they're open to working together. I strongly recommend pair programming but I wouldn't recommend working in a group larger than two.

**Comment by aparna-bhatt** [comment]
Ok sir ! It would be great to work on this issue together with @aashimawadhwa .
