### ISSUE TITLE
DICOM viewer with info ... tags scroll off and view resizes

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/ChRIS_ui#522]

**Comment by codeEmpress1** [comment]
@rudolphpienaar can you please explain this issue better, if possible show a screenshot. I will like to work on it. I'm an Outreachy applicant.

**Comment by jennydaman** [comment]
@codeEmpress1 DICOM is a medical imaging file format. You can see some example files in here: https://next.chrisproject.org/feeds/1549, login as the user `chris:chris1234`. In the bottom-left pane, click on any file ending in .dcm, then in the bottom-right pane, click on "Open Image Viewer."

![image](https://user-images.githubusercontent.com/20404439/195260546-31387aa4-f97c-4bd7-8567-ebf322959857.png)

Assuming this issue is no longer relevant, closing.
