### ISSUE TITLE
Navigate to correct library card from feed detail tree view

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/ChRIS_ui#590]

**Comment by rudolphpienaar** [comment]
![Image](https://user-images.githubusercontent.com/404964/184407964-f7d298c5-3c65-4efe-8070-fb6866b924b7.png)

**Comment by rudolphpienaar** [comment]
Need to add the shopping cart to this experience?

**Comment by PintoGideon** [comment]
Hey there @TateDeVito ,

This issue is a bit more involved but I'll do my best to explain it here. Feel free to reach out for more questions.

When you login into the ChRIS_ui and navigate to the library page,  you'll be able to see all your feeds in the Completed Analyses Tab.


![Screenshot from 2022-09-12 15-48-03](https://user-images.githubusercontent.com/15992276/189742639-8403c002-de0d-437b-8eb9-c08eeb730ccc.png)



![Screenshot from 2022-09-12 15-46-34](https://user-images.githubusercontent.com/15992276/189742644-af7be8ea-0d9e-459e-8e23-d3d00c1ca349.png)






You'll also see the same feeds in a tabular form in the New and Existing Analyses. When you click on the feed name, you will be able to see the detailed view of that feed. This task involves adding a 'button' to the Feed View page which on clicking will navigate to the corresponding feed in the Library Page.

![Screenshot from 2022-09-12 15-46-39](https://user-images.githubusercontent.com/15992276/189742642-58760a2a-e163-438c-988b-0d7d029e4afc.png)

![Screenshot from 2022-09-12 15-46-52](https://user-images.githubusercontent.com/15992276/189742640-526c662c-bd84-4ce1-9a9b-012503158dee.png)

![Screenshot from 2022-09-12 15-46-19](https://user-images.githubusercontent.com/15992276/189742645-7eafd564-c0ca-48d4-8e60-39a1858a30bd.png)

**Comment by TateDeVito** [comment]
Ok got it thank you @PintoGideon !

So to clarify, this task is to add a button in the feed view (tree format view) that takes you to the library page of that node you are highlighting.

If this is correct, curious where exactly you want the button? Would that be on the side with the "Add ChildNode" and "Add a Pipeline" buttons? And in the same format I assume?

**Comment by PintoGideon** [comment]
Yes, add a button to the panel with our buttons. I think there would be scope for redesigning that panel in the future, but the core functionality of being able to achieve is what we are after.

**Comment by TateDeVito** [comment]
Great. I will try to take a stab at this one. Thanks!

**Comment by TateDeVito** [comment]
Notes from MOC meeting:
- Use upload file option to populate new nodes
- The **Cancel** button at the end of the "New Analysis" dialog should say **Done**
