### ISSUE TITLE
Linting and code formatting automation

### ISSUE THREAD

**Issue by JulianaSau** [FNNDSC/ChRIS_ui#685]
I'd like to implement automation of linting and formatting on code using `husky` to create `pre-commit` and `pre-push` hooks to ensure that every developer contributing to this project is able to push code that is clean and bug-free.
This can be achieved using `prettier` and `lint-staged` to fix any syntactic and semantic errors on staged changes.

If this is a feature that would be beneficial to this project, I would like to take it on
@jennydaman

**Comment by jennydaman** [comment]
Yes this would be useful, related to https://github.com/FNNDSC/ChRIS_ui/issues/698

It is challenging since we would want to merge https://github.com/FNNDSC/ChRIS_ui/pull/700, but in a way without disturbing every other PR. That might entail waiting until after I am able to review everything in one go... Please be in contact with the author of #700 about using hooks, CI, ...

**Comment by Jolzyfx** [comment]
@jennydaman I would love to collaborate on this project with you, I'll be really glad if you can assign this to me. Thank You
