### ISSUE TITLE
keyboard shortcuts only work when top-left pane is focused

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#791]
![image](https://user-images.githubusercontent.com/20404439/212318749-0eb1ce81-de7b-45b7-8f5a-a41389ab3b94.png)

The keyboard shortcuts only work after I click in the top-left pane. If I click anywhere in the background of the top-right pane or the file browser, the keyboard shortcuts C, P, F, T, G stop working. There is no indication to the user that the top-left pane _must_ be focused for keyboard shortcuts to be applicable (neither do I think should the focused element be a limitation to the availability of these shortcuts).

**Comment by PintoGideon** [comment]
Hey @jennydaman , The reason the shortcuts only work when you are interacting with the tree is so that those keyboard keys are available to you when you use them for other purposes. Maybe an indicator to have the left pane focused would be better for now. A bug observed yesterday after adding an event listener to the entire page was that the events would fire when Rudolph would enter a text in the input field. Though this can be fixed, it would mean more thought and work on part of us.
